export class bulkdatas {
    constructor() { }
    states!:any;
    cities!:any;
    ugdegrees!:any;
    pgdegrees!:any;
    years!:any;
    salary!:any;
    role!:any;
    doSomething(): void {
      console.log('Hello from MyClass!');
      //state
      this.states = [
        { name: 'Andhra Pradesh', value: 'Andhra Pradesh' },
        { name: 'Assam', value: 'Assam' },
        { name: 'Bihar', value: 'Bihar' },
        { name: 'Chhattisgarh', value: 'Chhattisgarh' },
        { name: 'Goa', value: 'Goa' },
        { name: 'Gujarat', value: 'Gujarat' },
        { name: 'Haryana', value: 'Haryana' },
        { name: 'Himachal Pradesh', value: 'Himachal Pradesh' },
        { name: 'Jharkhand', value: 'Jharkhand' },
        { name: 'Karnataka', value: 'Karnataka' },
        { name: 'Kerala', value: 'Kerala' },
        { name: 'Madhya Pradesh', value: 'Madhya Pradesh' },
        { name: 'Maharashtra', value: 'Maharashtra' },
        { name: 'Manipur', value: 'Manipur' },
        { name: 'Meghalaya', value: 'Meghalaya' },
        { name: 'Mizoram', value: 'Mizoram' },
        { name: 'Nagaland', value: 'Nagaland' },
        { name: 'Odisha', value: 'Odisha' },
        { name: 'Punjab', value: 'Punjab' },
        { name: 'Rajasthan', value: 'Rajasthan' },
        { name: 'Sikkim', value: 'Sikkim' },
        { name: 'Tamil Nadu', value: 'Tamil Nadu' },
        { name: 'Telangana', value: 'Telangana' },
        { name: 'Tripura', value: 'Tripura' },
        { name: 'Uttar Pradesh', value: 'Uttar Pradesh' },
        { name: 'Uttarakhand', value: 'Uttarakhand' },
        { name: 'West Bengal', value: 'West Bengal' },
        { name: 'Andaman and Nicobar Islands', value: 'Andaman and Nicobar Islands' },
        { name: 'Chandigarh', value: 'Chandigarh' },
        { name: 'Dadra and Nagar Haveli and Daman and Diu', value: 'Dadra and Nagar Haveli and Daman and Diu' },
        { name: 'Lakshadweep', value: 'Lakshadweep' },
        { name: 'Delhi', value: 'Delhi' },
        { name: 'Pondicherry', value: 'Pondicherry' },
        { name: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
        { name: 'Ladakh', value: 'Ladakh' }
      ];


        //city
        this.cities =[
          {
            name: 'Andhra Pradesh',
            cities: [
              { name: 'Anantapur',value:'Anantapur' },
        { name: 'Chittoor',value:'Chittoor' },
        { name: 'East Godavari',value:'East Godavari' },
        { name: 'Guntur',value:'Guntur' },
        { name: 'Krishna',value:'Krishna' },
        { name: 'Kurnool',value:'Kurnool' },
        { name: 'Nellore',value:'Nellore' },
        { name: 'Prakasam',value:'Prakasam' },
        { name: 'Srikakulam',value:'Srikakulam' },
        { name: 'Visakhapatnam',value:'Visakhapatnam' },
        { name: 'Vizianagaram',value:'Vizianagaram' },
        { name: 'West Godavari',value:'West Godavari' },
        { name: 'YSR Kadapa',value:'YSR Kadapa' },
        
         
            ]
          },
          {
            name: 'Assam',
            cities: [
              { name: 'Baksa',value:'Baksa' },
        { name: 'Barpeta',value:'Barpeta' },
        { name: 'Biswanath',value:'Biswanath' },
        { name: 'Bongaigaon',value:'Bongaigaon' },
        { name: 'Cachar',value:'Cachar' },
        { name: 'Charaideo',value:'Charaideo' },
        { name: 'Chirang',value:'Chirang' },
        { name: 'Darrang',value:'Darrang' },
        { name: 'Dhemaji',value:'Dhemaji' },
        { name: 'Dhubri',value:'Dhubri' },
        { name: 'Dibrugarh',value:'Dibrugarh' },
        { name: 'Dima Hasao (North Cachar Hills)',value:'Dima Hasao (North Cachar Hills)' },
        { name: 'Goalpara',value:'Goalpara' },
        { name: 'Golaghat',value:'Golaghat' },
        { name: 'Hailakandi',value:'Hailakandi' },
        { name: 'Hojai',value:'Hojai' },
        { name: 'Jorhat',value:'Jorhat' },
        { name: 'Kamrup Metropolitan',value:'Kamrup Metropolitan' },
        { name: 'Kamrup',value:'Kamrup' },
        { name: 'Karbi Anglong',value:'Karbi Anglong' },
        { name: 'Karimganj',value:'Karimganj' },
        { name: 'Kokrajhar',value:'Kokrajhar' },
        { name: 'Lakhimpur',value:'Lakhimpur' },
        { name: 'Majuli',value:'Majuli' },
        { name: 'Morigaon',value:'Morigaon' },
        { name: 'Nagaon',value:'Nagaon' },
        { name: 'Nalbari',value:'Nalbari' },
        { name: 'Sivasagar',value:'Sivasagar' },
        { name: 'Sonitpur',value:'Sonitpur' },
        { name: 'South Salmara-Mankachar',value:'South Salmara-Mankachar' },
        { name: 'Tinsukia',value:'Tinsukia' },
        { name: 'Udalguri',value:'Udalguri' },
        { name: 'West Karbi Anglong',value:'West Karbi Anglong' },
        
        
             
            ]
          },
          {
            name: 'Bihar',
            cities: [
              { name: 'Araria',value:'Araria' },
        { name: 'Arwal',value:'Arwal' },
        { name: 'Aurangabad',value:'Aurangabad' },
        { name: 'Banka',value:'Banka' },
        { name: 'Begusarai',value:'Begusarai' },
        { name: 'Bhagalpur',value:'Bhagalpur' },
        { name: 'Bhojpur',value:'Bhojpur' },
        { name: 'Buxar',value:'Buxar' },
        { name: 'Darbhanga',value:'Darbhanga' },
        { name: 'East Champaran (Motihari)',value:'East Champaran (Motihari)' },
        { name: 'Gaya',value:'Gaya' },
        { name: 'Gopalganj',value:'Gopalganj' },
        { name: 'Jamui',value:'Jamui' },
        { name: 'Jehanabad',value:'Jehanabad' },
        { name: 'Kaimur (Bhabua)',value:'Kaimur (Bhabua)' },
        { name: 'Katihar',value:'Katihar' },
        { name: 'Khagaria',value:'Khagaria' },
        { name: 'Kishanganj',value:'Kishanganj' },
        { name: 'Lakhisarai',value:'Lakhisarai' },
        { name: 'Madhepura',value:'Madhepura' },
        { name: 'Madhubani',value:'Madhubani' },
        { name: 'Munger (Monghyr)',value:'Munger (Monghyr)' },
        { name: 'Muzaffarpur',value:'Muzaffarpur' },
        { name: 'Nalanda',value:'Nalanda' },
        { name: 'Nawada',value:'Nawada' },
        { name: 'Patna',value:'Patna' },
        { name: 'Purnia (Purnea)',value:'Purnia (Purnea)' },
        { name: 'Rohtas',value:'Rohtas' },
        { name: 'Saharsa',value:'Saharsa' },
        { name: 'Samastipur',value:'Samastipur' },
        { name: 'Saran',value:'Saran' },
        { name: 'Sheikhpura',value:'Sheikhpura' },
        { name: 'Sheohar',value:'Sheohar' },
        
        
             
            ]
          },
          {
            name: 'Chhattisgarh',
            cities: [
              { name: 'Balod',value:'Balod' },
        { name: 'Baloda Bazar',value:'Baloda Bazar' },
        { name: 'Balrampur',value:'Balrampur' },
        { name: 'Bastar',value:'Bastar' },
        { name: 'Bemetara',value:'Bemetara' },
        { name: 'Bijapur',value:'Bijapur' },
        { name: 'Bilaspur',value:'Bilaspur' },
        { name: 'Dantewada (South Bastar)',value:'Dantewada (South Bastar)' },
        { name: 'Dhamtari',value:'Dhamtari' },
        { name: 'Durg',value:'Durg' },
        { name: 'Gariaband',value:'Gariaband' },
        { name: 'Janjgir-Champa',value:'Janjgir-Champa' },
        { name: 'Jashpur',value:'Jashpur' },
        { name: 'Kabirdham (Kawardha)',value:'Kabirdham (Kawardha)' },
        { name: 'Kanker (North Bastar)',value:'Kanker (North Bastar)' },
        { name: 'Kondagaon',value:'Kondagaon' },
        { name: 'Korba',value:'Korba' },
        { name: 'Korea (Koriya)',value:'Korea (Koriya)' },
        { name: 'Mahasamund',value:'Mahasamund' },
        { name: 'Mungeli',value:'Mungeli' },
        { name: 'Narayanpur',value:'Narayanpur' },
        { name: 'Raigarh',value:'Raigarh' },
        { name: 'Raipur',value:'Raipur' },
        { name: 'Rajnandgaon',value:'Rajnandgaon' },
        { name: 'Sukma',value:'Sukma' },
        { name: 'Surajpur',value:'Surajpur' },
        { name: 'Surguja',value:'Surguja' },
        { name: 'Baloda',value:'Baloda' },
        
        
             
            ]
          },
          {
            name: 'Goa',
            cities: [
              { name: 'North Goa',value:'North Goa' },
        { name: 'South Goa',value:'South Goa' },
        
        
             
            ]
          },
          {
            name: 'Gujarat',
            cities: [
              { name: 'Ahmedabad',value:'Ahmedabad' },
        { name: 'Amreli',value:'Amreli' },
        { name: 'Anand',value:'Anand' },
        { name: 'Aravalli',value:'Aravalli' },
        { name: 'Banaskantha',value:'Banaskantha' },
        { name: 'Bharuch',value:'Bharuch' },
        { name: 'Bhavnagar',value:'Bhavnagar' },
        { name: 'Botad',value:'Botad' },
        { name: 'Chhota Udaipur',value:'Chhota Udaipur' },
        { name: 'Dahod',value:'Dahod' },
        { name: 'Dang',value:'Dang' },
        { name: 'Devbhoomi Dwarka',value:'Devbhoomi Dwarka' },
        { name: 'Gandhinagar',value:'Gandhinagar' },
        { name: 'Gir Somnath',value:'Gir Somnath' },
        { name: 'Jamnagar',value:'Jamnagar' },
        { name: 'Junagadh',value:'Junagadh' },
        { name: 'Kheda',value:'Kheda' },
        { name: 'Kutch',value:'Kutch' },
        { name: 'Mahisagar',value:'Mahisagar' },
        { name: 'Mehsana',value:'Mehsana' },
        { name: 'Morbi',value:'Morbi' },
        { name: 'Narmada',value:'Narmada' },
        { name: 'Navsari',value:'Navsari' },
        { name: 'Panchmahal',value:'Panchmahal' },
        { name: 'Patan',value:'Patan' },
        { name: 'Porbandar',value:'Porbandar' },
        { name: 'Rajkot',value:'Rajkot' },
        { name: 'Sabarkantha',value:'Sabarkantha' },
        { name: 'Surat',value:'Surat' },
        { name: 'Surendranagar',value:'Surendranagar' },
        { name: 'Tapi',value:'Tapi' },
        { name: 'Vadodara',value:'Vadodara' },
        { name: 'Valsad',value:'Valsad' },
        
        
             
            ]
          },{
            name: 'Haryana',
            cities: [
              { name: 'Ambala',value:'Ambala' },
        { name: 'Bhiwani',value:'Bhiwani' },
        { name: 'Charkhi Dadri',value:'Charkhi Dadri' },
        { name: 'Faridabad',value:'Faridabad' },
        { name: 'Fatehabad',value:'Fatehabad' },
        { name: 'Gurugram',value:'Gurugram' },
        { name: 'Hisar',value:'Hisar' },
        { name: 'Jhajjar',value:'Jhajjar' },
        { name: 'Jind',value:'Jind' },
        { name: 'Kaithal',value:'Kaithal' },
        { name: 'Karnal',value:'Karnal' },
        { name: 'Kurukshetra',value:'Kurukshetra' },
        { name: 'Mahendragarh',value:'Mahendragarh' },
        { name: 'Nuh',value:'Nuh' },
        { name: 'Palwal',value:'Palwal' },
        { name: 'Panchkula',value:'Panchkula' },
        { name: 'Panipat',value:'Panipat' },
        { name: 'Rewari',value:'Rewari' },
        { name: 'Rohtak',value:'Rohtak' },
        { name: 'Sirsa',value:'Sirsa' },
        { name: 'Sonipat',value:'Sonipat' },
        { name: 'Yamunanagar',value:'Yamunanagar' },
        
        
             
            ]
          },{
            name: 'Himachal Pradesh',
            cities: [
              { name: 'Bilaspur',value:'Bilaspur' },
        { name: 'Chamba',value:'Chamba' },
        { name: 'Hamirpur',value:'Hamirpur' },
        { name: 'Kangra',value:'Kangra' },
        { name: 'Kinnaur',value:'Kinnaur' },
        { name: 'Kullu',value:'Kullu' },
        { name: 'Lahaul and Spiti',value:'Lahaul and Spiti' },
        { name: 'Mandi',value:'Mandi' },
        { name: 'Shimla',value:'Shimla' },
        { name: 'Sirmaur',value:'Sirmaur' },
        { name: 'Solan',value:'Solan' },
        { name: 'Una',value:'Una' },
        
        
             
            ]
          },{
            name: 'Jharkhand',
            cities: [
              { name: 'Bokaro',value:'Bokaro' },
        { name: 'Chatra',value:'Chatra' },
        { name: 'Deoghar',value:'Deoghar' },
        { name: 'Dhanbad',value:'Dhanbad' },
        { name: 'Dumka',value:'Dumka' },
        { name: 'East Singhbhum',value:'East Singhbhum' },
        { name: 'Garhwa',value:'Garhwa' },
        { name: 'Giridih',value:'Giridih' },
        { name: 'Godda',value:'Godda' },
        { name: 'Gumla',value:'Gumla' },
        { name: 'Hazaribagh',value:'Hazaribagh' },
        { name: 'Jamtara',value:'Jamtara' },
        { name: 'Khunti',value:'Khunti' },
        { name: 'Koderma',value:'Koderma' },
        { name: 'Latehar',value:'Latehar' },
        { name: 'Lohardaga',value:'Lohardaga' },
        { name: 'Pakur',value:'Pakur' },
        { name: 'Palamu',value:'Palamu' },
        { name: 'Ramgarh',value:'Ramgarh' },
        { name: 'Ranchi',value:'Ranchi' },
        { name: 'Sahibganj',value:'Sahibganj' },
        { name: 'Seraikela Kharsawan',value:'Seraikela Kharsawan' },
        { name: 'Simdega',value:'Simdega' },
        { name: 'West Singhbhum',value:'West Singhbhum' },
        
        
             
            ]
          },{
            name: 'Karnataka',
            cities: [
              { name: 'Bagalkot',value:'Bagalkot' },
        { name: 'Ballari (Bellary)',value:'Ballari (Bellary)' },
        { name: 'Belagavi (Belgaum)',value:'Belagavi (Belgaum)' },
        { name: 'Bengaluru (Bangalore) Rural',value:'Bengaluru (Bangalore) Rural' },
        { name: 'Bengaluru (Bangalore) Urban',value:'Bengaluru (Bangalore) Urban' },
        { name: 'Bidar',value:'Bidar' },
        { name: 'Vijayapura (Bijapur)',value:'Vijayapura (Bijapur)' },
        { name: 'Chamarajanagara',value:'Chamarajanagara' },
        { name: 'Chikballapur',value:'Chikballapur' },
        { name: 'Chikkamagaluru (Chikmagalur)',value:'Chikkamagaluru (Chikmagalur)' },
        { name: 'Chitradurga',value:'Chitradurga' },
        { name: 'Dakshina Kannada',value:'Dakshina Kannada' },
        { name: 'Davangere',value:'Davangere' },
        { name: 'Dharwad',value:'Dharwad' },
        { name: 'Gadag',value:'Gadag' },
        { name: 'Kalaburagi (Gulbarga)',value:'Kalaburagi (Gulbarga)' },
        { name: 'Hassan',value:'Hassan' },
        { name: 'Haveri',value:'Haveri' },
        { name: 'Kodagu',value:'Kodagu' },
        { name: 'Kolar',value:'Kolar' },
        { name: 'Koppal',value:'Koppal' },
        { name: 'Mandya',value:'Mandya' },
        { name: 'Mysuru (Mysore)',value:'Mysuru (Mysore)' },
        { name: 'Raichur',value:'Raichur' },
        { name: 'Ramanagara',value:'Ramanagara' },
        { name: 'Shivamogga (Shimoga)',value:'Shivamogga (Shimoga)' },
        { name: 'Tumakuru (Tumkur)',value:'Tumakuru (Tumkur)' },
        { name: 'Udupi',value:'Udupi' },
        { name: 'Uttara Kannada (Karwar)',value:'Uttara Kannada (Karwar)' },
        { name: 'Yadgir',value:'Yadgir' },
        
        
             
            ]
          },{
            name: 'Kerala',
            cities: [
             { name: 'Alappuzha',value:'Alappuzha' },
        { name: 'Ernakulam',value:'Ernakulam' },
        { name: 'Idukki',value:'Idukki' },
        { name: 'Kannur',value:'Kannur' },
        { name: 'Kasaragod',value:'Kasaragod' },
        { name: 'Kollam',value:'Kollam' },
        { name: 'Kottayam',value:'Kottayam' },
        { name: 'Kozhikode',value:'Kozhikode' },
        { name: 'Malappuram',value:'Malappuram' },
        { name: 'Palakkad',value:'Palakkad' },
        { name: 'Pathanamthitta',value:'Pathanamthitta' },
        { name: 'Thiruvananthapuram',value:'Thiruvananthapuram' },
        { name: 'Thrissur',value:'Thrissur' },
        { name: 'Wayanad',value:'Wayanad' },
        
        
             
            ]
          },{
            name: 'Madhya Pradesh',
            cities: [
              { name: 'Agar Malwa',value:'Agar Malwa' },
        { name: 'Alirajpur',value:'Alirajpur' },
        { name: 'Anuppur',value:'Anuppur' },
        { name: 'Ashoknagar',value:'Ashoknagar' },
        { name: 'Balaghat',value:'Balaghat' },
        { name: 'Barwani',value:'Barwani' },
        { name: 'Betul',value:'Betul' },
        { name: 'Bhind',value:'Bhind' },
        { name: 'Bhopal',value:'Bhopal' },
        { name: 'Burhanpur',value:'Burhanpur' },
        { name: 'Chhatarpur',value:'Chhatarpur' },
        { name: 'Chhindwara',value:'Chhindwara' },
        { name: 'Damoh',value:'Damoh' },
        { name: 'Datia',value:'Datia' },
        { name: 'Dewas',value:'Dewas' },
        { name: 'Dhar',value:'Dhar' },
        { name: 'Dindori',value:'Dindori' },
        { name: 'Guna',value:'Guna' },
        { name: 'Gwalior',value:'Gwalior' },
        { name: 'Harda',value:'Harda' },
        { name: 'Hoshangabad',value:'Hoshangabad' },
        { name: 'Indore',value:'Indore' },
        { name: 'Jabalpur',value:'Jabalpur' },
        { name: 'Jhabua',value:'Jhabua' },
        { name: 'Katni',value:'Katni' },
        { name: 'Khandwa',value:'Khandwa' },
        { name: 'Khargone',value:'Khargone' },
        { name: 'Mandla',value:'Mandla' },
        { name: 'Mandsaur',value:'Mandsaur' },
        { name: 'Morena',value:'Morena' },
        { name: 'Narsinghpur',value:'Narsinghpur' },
        { name: 'Neemuch',value:'Neemuch' },
        { name: 'Niwari',value:'Niwari' },
        { name: 'Panna',value:'Panna' },
        { name: 'Raisen',value:'Raisen' },
        { name: 'Rajgarh',value:'Rajgarh' },
        { name: 'Ratlam',value:'Ratlam' },
        { name: 'Rewa',value:'Rewa' },
        { name: 'Sagar',value:'Sagar' },
        { name: 'Satna',value:'Satna' },
        { name: 'Sehore',value:'Sehore' },
        { name: 'Seoni',value:'Seoni' },
        { name: 'Shahdol',value:'Shahdol' },
        { name: 'Shajapur',value:'Shajapur' },
        { name: 'Sheopur',value:'Sheopur' },
        { name: 'Shivpuri',value:'Shivpuri' },
        { name: 'Sidhi',value:'Sidhi' },
        { name: 'Singrauli',value:'Singrauli' },
        { name: 'Tikamgarh',value:'Tikamgarh' },
        { name: 'Ujjain',value:'Ujjain' },
        { name: 'Umaria',value:'Umaria' },
        { name: 'Vidisha',value:'Vidisha' },
        
        
             
            ]
          },
          {
            name: 'Maharashtra',
            cities: [
              { name: 'Ahmednagar',value:'Ahmednagar' },
        { name: 'Akola',value:'Akola' },
        { name: 'Amravati',value:'Amravati' },
        { name: 'Aurangabad',value:'Aurangabad' },
        { name: 'Beed',value:'Beed' },
        { name: 'Bhandara',value:'Bhandara' },
        { name: 'Buldhana',value:'Buldhana' },
        { name: 'Chandrapur',value:'Chandrapur' },
        { name: 'Dhule',value:'Dhule' },
        { name: 'Gadchiroli',value:'Gadchiroli' },
        { name: 'Gondia',value:'Gondia' },
        { name: 'Hingoli',value:'Hingoli' },
        { name: 'Jalgaon',value:'Jalgaon' },
        { name: 'Jalna',value:'Jalna' },
        { name: 'Kolhapur',value:'Kolhapur' },
        { name: 'Latur',value:'Latur' },
        { name: 'Mumbai City',value:'Mumbai City' },
        { name: 'Mumbai Suburban',value:'Mumbai Suburban' },
        { name: 'Nagpur',value:'Nagpur' },
        { name: 'Nanded',value:'Nanded' },
        { name: 'Nandurbar',value:'Nandurbar' },
        { name: 'Nashik',value:'Nashik' },
        { name: 'Osmanabad',value:'Osmanabad' },
        { name: 'Palghar',value:'Palghar' },
        { name: 'Parbhani',value:'Parbhani' },
        { name: 'Pune',value:'Pune' },
        { name: 'Raigad',value:'Raigad' },
        { name: 'Ratnagiri',value:'Ratnagiri' },
        { name: 'Sangli',value:'Sangli' },
        { name: 'Satara',value:'Satara' },
        { name: 'Sindhudurg',value:'Sindhudurg' },
        { name: 'Solapur',value:'Solapur' },
        { name: 'Thane',value:'Thane' },
        { name: 'Wardha',value:'Wardha' },
        { name: 'Washim',value:'Washim' },
        { name: 'Yavatmal',value:'Yavatmal' },
        
        
             
            ]
          },
          {
            name: 'Manipur',
            cities: [
              { name: 'Bishnupur',value:'Bishnupur' },
        { name: 'Chandel',value:'Chandel' },
        { name: 'Churachandpur',value:'Churachandpur' },
        { name: 'Imphal East',value:'Imphal East' },
        { name: 'Imphal West',value:'Imphal West' },
        { name: 'Jiribam',value:'Jiribam' },
        { name: 'Kakching',value:'Kakching' },
        { name: 'Kamjong',value:'Kamjong' },
        { name: 'Kangpokpi',value:'Kangpokpi' },
        { name: 'Noney',value:'Noney' },
        { name: 'Pherzawl',value:'Pherzawl' },
        { name: 'Senapati',value:'Senapati' },
        { name: 'Tamenglong',value:'Tamenglong' },
        { name: 'Tengnoupal',value:'Tengnoupal' },
        { name: 'Thoubal',value:'Thoubal' },
        { name: 'Ukhrul',value:'Ukhrul' },
        
        
             
            ]
          },
          {
            name: 'Meghalaya',
            cities: [
              { name: 'East Garo Hills',value:'East Garo Hills' },
        { name: 'East Jaintia Hills',value:'East Jaintia Hills' },
        { name: 'East Khasi Hills',value:'East Khasi Hills' },
        { name: 'North Garo Hills',value:'North Garo Hills' },
        { name: 'Ri Bhoi',value:'Ri Bhoi' },
        { name: 'South Garo Hills',value:'South Garo Hills' },
        { name: 'South West Garo Hills',value:'South West Garo Hills' },
        { name: 'South West Khasi Hills',value:'South West Khasi Hills' },
        { name: 'West Garo Hills',value:'West Garo Hills' },
        { name: 'West Jaintia Hills',value:'West Jaintia Hills' },
        { name: 'West Khasi Hills',value:'West Khasi Hills' },
        
        
             
            ]
          },
          {
            name: 'Mizoram',
            cities: [
              { name: 'Aizawl',value:'Aizawl' },
        { name: 'Champhai',value:'Champhai' },
        { name: 'Kolasib',value:'Kolasib' },
        { name: 'Lawngtlai',value:'Lawngtlai' },
        { name: 'Lunglei',value:'Lunglei' },
        { name: 'Mamit',value:'Mamit' },
        { name: 'Saiha',value:'Saiha' },
        { name: 'Serchhip',value:'Serchhip' },
        { name: 'Hnahthial',value:'Hnahthial' },
        { name: 'Khawzawl',value:'Khawzawl' },
        { name: 'Saitual',value:'Saitual' },
        
        
             
            ]
          },
          {
            name: 'Nagaland',
            cities: [
              { name: 'Dimapur',value:'Dimapur' },
        { name: 'Kiphire',value:'Kiphire' },
        { name: 'Kohima',value:'Kohima' },
        { name: 'Longleng',value:'Longleng' },
        { name: 'Mokokchung',value:'Mokokchung' },
        { name: 'Mon',value:'Mon' },
        { name: 'Peren',value:'Peren' },
        { name: 'Phek',value:'Phek' },
        { name: 'Tuensang',value:'Tuensang' },
        { name: 'Wokha',value:'Wokha' },
        { name: 'Zunheboto',value:'Zunheboto' },
        
        
             
            ]
          },
          {
            name: 'Odisha',
            cities: [
              { name: 'Angul',value:'Angul' },
        { name: 'Balangir',value:'Balangir' },
        { name: 'Balasore',value:'Balasore' },
        { name: 'Bargarh',value:'Bargarh' },
        { name: 'Bhadrak',value:'Bhadrak' },
        { name: 'Boudh',value:'Boudh' },
        { name: 'Cuttack',value:'Cuttack' },
        { name: 'Deogarh',value:'Deogarh' },
        { name: 'Dhenkanal',value:'Dhenkanal' },
        { name: 'Gajapati',value:'Gajapati' },
        { name: 'Ganjam',value:'Ganjam' },
        { name: 'Jagatsinghpur',value:'Jagatsinghpur' },
        { name: 'Jajpur',value:'Jajpur' },
        { name: 'Jharsuguda',value:'Jharsuguda' },
        { name: 'Kalahandi',value:'Kalahandi' },
        { name: 'Kandhamal',value:'Kandhamal' },
        { name: 'Kendrapara',value:'Kendrapara' },
        { name: 'Kendujhar (Keonjhar)',value:'Kendujhar (Keonjhar)' },
        { name: 'Khordha',value:'Khordha' },
        { name: 'Koraput',value:'Koraput' },
        { name: 'Malkangiri',value:'Malkangiri' },
        { name: 'Mayurbhanj',value:'Mayurbhanj' },
        { name: 'Nabarangpur',value:'Nabarangpur' },
        { name: 'Nayagarh',value:'Nayagarh' },
        { name: 'Nuapada',value:'Nuapada' },
        { name: 'Puri',value:'Puri' },
        { name: 'Rayagada',value:'Rayagada' },
        { name: 'Sambalpur',value:'Sambalpur' },
        { name: 'Subarnapur (Sonepur)',value:'Subarnapur (Sonepur)' },
        { name: 'Sundergarh',value:'Sundergarh' },
        
        
             
            ]
          },
          {
            name: 'Punjab',
            cities: [
              { name: 'Amritsar',value:'Amritsar' },
        { name: 'Barnala',value:'Barnala' },
        { name: 'Bathinda',value:'Bathinda' },
        { name: 'Faridkot',value:'Faridkot' },
        { name: 'Fatehgarh Sahib',value:'Fatehgarh Sahib' },
        { name: 'Fazilka',value:'Fazilka' },
        { name: 'Ferozepur',value:'Ferozepur' },
        { name: 'Gurdaspur',value:'Gurdaspur' },
        { name: 'Hoshiarpur',value:'Hoshiarpur' },
        { name: 'Jalandhar',value:'Jalandhar' },
        { name: 'Kapurthala',value:'Kapurthala' },
        { name: 'Ludhiana',value:'Ludhiana' },
        { name: 'Mansa',value:'Mansa' },
        { name: 'Moga',value:'Moga' },
        { name: 'Muktsar',value:'Muktsar' },
        { name: 'Pathankot',value:'Pathankot' },
        { name: 'Patiala',value:'Patiala' },
        { name: 'Rupnagar',value:'Rupnagar' },
        { name: 'Sahibzada Ajit Singh Nagar (Mohali)',value:'Sahibzada Ajit Singh Nagar (Mohali)' },
        { name: 'Sangrur',value:'Sangrur' },
        { name: 'Shahid Bhagat Singh Nagar (Nawanshahr)',value:'Shahid Bhagat Singh Nagar (Nawanshahr)' },
        { name: 'Tarn Taran',value:'Tarn Taran' },
        
        
             
            ]
          },
          {
            name: 'Rajasthan',
            cities: [
              { name: 'Ajmer',value:'Ajmer' },
        { name: 'Alwar',value:'Alwar' },
        { name: 'Banswara',value:'Banswara' },
        { name: 'Baran',value:'Baran' },
        { name: 'Barmer',value:'Barmer' },
        { name: 'Bharatpur',value:'Bharatpur' },
        { name: 'Bhilwara',value:'Bhilwara' },
        { name: 'Bikaner',value:'Bikaner' },
        { name: 'Bundi',value:'Bundi' },
        { name: 'Chittorgarh',value:'Chittorgarh' },
        { name: 'Churu',value:'Churu' },
        { name: 'Dausa',value:'Dausa' },
        { name: 'Dholpur',value:'Dholpur' },
        { name: 'Dungarpur',value:'Dungarpur' },
        { name: 'Hanumangarh',value:'Hanumangarh' },
        { name: 'Jaipur',value:'Jaipur' },
        { name: 'Jaisalmer',value:'Jaisalmer' },
        { name: 'Jalor',value:'Jalor' },
        { name: 'Jhalawar',value:'Jhalawar' },
        { name: 'Jhunjhunu',value:'Jhunjhunu' },
        { name: 'Jodhpur',value:'Jodhpur' },
        { name: 'Karauli',value:'Karauli' },
        { name: 'Kota',value:'Kota' },
        { name: 'Nagaur',value:'Nagaur' },
        { name: 'Pali',value:'Pali' },
        { name: 'Pratapgarh',value:'Pratapgarh' },
        { name: 'Rajsamand',value:'Rajsamand' },
        { name: 'Sawai Madhopur',value:'Sawai Madhopur' },
        { name: 'Sikar',value:'Sikar' },
        { name: 'Sirohi',value:'Sirohi' },
        { name: 'Sri Ganganagar',value:'Sri Ganganagar' },
        { name: 'Tonk',value:'Tonk' },
        { name: 'Udaipur',value:'Udaipur' },
        
        
             
            ]
          },
          {
            name: 'Sikkim',
            cities: [
              { name: 'East Sikkim',value:'East Sikkim' },
        { name: 'North Sikkim',value:'North Sikkim' },
        { name: 'South Sikkim',value:'South Sikkim' },
        { name: 'West Sikkim',value:'West Sikkim' },
        
        
             
            ]
          },
          {
            name: 'Tamil Nadu',
            cities: [
              { name: 'Ariyalur',value:'Ariyalur' },
        { name: 'Chennai',value:'Chennai' },
        { name: 'Coimbatore',value:'Coimbatore' },
        { name: 'Cuddalore',value:'Cuddalore' },
        { name: 'Dharmapuri',value:'Dharmapuri' },
        { name: 'Dindigul',value:'Dindigul' },
        { name: 'Erode',value:'Erode' },
        { name: 'Kanchipuram',value:'Kanchipuram' },
        { name: 'Kanyakumari',value:'Kanyakumari' },
        { name: 'Karur',value:'Karur' },
        { name: 'Krishnagiri',value:'Krishnagiri' },
        { name: 'Madurai',value:'Madurai' },
        { name: 'Nagapattinam',value:'Nagapattinam' },
        { name: 'Namakkal',value:'Namakkal' },
        { name: 'Nilgiris',value:'Nilgiris' },
        { name: 'Perambalur',value:'Perambalur' },
        { name: 'Pudukkottai',value:'Pudukkottai' },
        { name: 'Ramanathapuram',value:'Ramanathapuram' },
        { name: 'Salem',value:'Salem' },
        { name: 'Sivaganga',value:'Sivaganga' },
        { name: 'Thanjavur',value:'Thanjavur' },
        { name: 'Theni',value:'Theni' },
        { name: 'Thoothukudi (Tuticorin)',value:'Thoothukudi (Tuticorin)' },
        { name: 'Tiruchirappalli (Trichy)',value:'Tiruchirappalli (Trichy)' },
        { name: 'Tirunelveli',value:'Tirunelveli' },
        { name: 'Tirupathur',value:'Tirupathur' },
        { name: 'Tiruppur',value:'Tiruppur' },
        { name: 'Tiruvallur',value:'Tiruvallur' },
        { name: 'Tiruvannamalai',value:'Tiruvannamalai' },
        { name: 'Tiruvarur',value:'Tiruvarur' },
        { name: 'Vellore',value:'Vellore' },
        { name: 'Viluppuram',value:'Viluppuram' },
        { name: 'Virudhunagar',value:'Virudhunagar' },
        { name: 'Chengalpattu',value:'Chengalpattu' },
        { name: 'Ranipet',value:'Ranipet' },
        { name: 'Tenkasi',value:'Tenkasi' },
        { name: 'Kallakurichi',value:'Kallakurichi' },
        { name: 'Mayiladuthurai',value:'Mayiladuthurai' },
        
        
             
            ]
          },
          {
            name: 'Telangana',
            cities: [
              { name: 'Adilabad',value:'Adilabad' },
        { name: 'Bhadradri Kothagudem',value:'Bhadradri Kothagudem' },
        { name: 'Hyderabad',value:'Hyderabad' },
        { name: 'Jagtial',value:'Jagtial' },
        { name: 'Jangaon',value:'Jangaon' },
        { name: 'Jayashankar Bhupalapally',value:'Jayashankar Bhupalapally' },
        { name: 'Jogulamba Gadwal',value:'Jogulamba Gadwal' },
        { name: 'Kamareddy',value:'Kamareddy' },
        { name: 'Karimnagar',value:'Karimnagar' },
        { name: 'Khammam',value:'Khammam' },
        { name: 'Komaram Bheem Asifabad',value:'Komaram Bheem Asifabad' },
        { name: 'Mahabubabad',value:'Mahabubabad' },
        { name: 'Mahabubnagar',value:'Mahabubnagar' },
        { name: 'Mancherial',value:'Mancherial' },
        { name: 'Medak',value:'Medak' },
        { name: 'Medchal Malkajgiri',value:'Medchal Malkajgiri' },
        { name: 'Mulugu',value:'Mulugu' },
        { name: 'Nagarkurnool',value:'Nagarkurnool' },
        { name: 'Nalgonda',value:'Nalgonda' },
        { name: 'Narayanpet',value:'Narayanpet' },
        { name: 'Nirmal',value:'Nirmal' },
        { name: 'Nizamabad',value:'Nizamabad' },
        { name: 'Peddapalli',value:'Peddapalli' },
        { name: 'Rajanna Sircilla',value:'Rajanna Sircilla' },
        { name: 'Ranga Reddy',value:'Ranga Reddy' },
        { name: 'Sangareddy',value:'Sangareddy' },
        { name: 'Siddipet',value:'Siddipet' },
        { name: 'Suryapet',value:'Suryapet' },
        { name: 'Vikarabad',value:'Vikarabad' },
        { name: 'Wanaparthy',value:'Wanaparthy' },
        { name: 'Warangal Rural',value:'Warangal Rural' },
        { name: 'Warangal Urban',value:'Warangal Urban' },
        { name: 'Yadadri Bhuvanagiri',value:'Yadadri Bhuvanagiri' },
        
        
             
            ]
          },
          {
            name: 'Tripura',
            cities: [
             { name: 'Dhalai',value:'Dhalai' },
        { name: 'Gomati',value:'Gomati' },
        { name: 'Khowai',value:'Khowai' },
        { name: 'North Tripura',value:'North Tripura' },
        { name: 'Sepahijala',value:'Sepahijala' },
        { name: 'South Tripura',value:'South Tripura' },
        { name: 'Unakoti',value:'Unakoti' },
        { name: 'West Tripura',value:'West Tripura' },
        
        
             
            ]
          },
          {
            name: 'Uttar Pradesh',
            cities: [
              { name: 'Agra',value:'Agra' },
        { name: 'Aligarh',value:'Aligarh' },
        { name: 'Allahabad',value:'Allahabad' },
        { name: 'Ambedkar Nagar',value:'Ambedkar Nagar' },
        { name: 'Amethi',value:'Amethi' },
        { name: 'Amroha',value:'Amroha' },
        { name: 'Auraiya',value:'Auraiya' },
        { name: 'Azamgarh',value:'Azamgarh' },
        { name: 'Baghpat',value:'Baghpat' },
        { name: 'Bahraich',value:'Bahraich' },
        { name: 'Ballia',value:'Ballia' },
        { name: 'Balrampur',value:'Balrampur' },
        { name: 'Banda',value:'Banda' },
        { name: 'Barabanki',value:'Barabanki' },
        { name: 'Bareilly',value:'Bareilly' },
        { name: 'Basti',value:'Basti' },
        { name: 'Bhadohi',value:'Bhadohi' },
        { name: 'Bijnor',value:'Bijnor' },
        { name: 'Budaun',value:'Budaun' },
        { name: 'Bulandshahr',value:'Bulandshahr' },
        { name: 'Chandauli',value:'Chandauli' },
        { name: 'Chitrakoot',value:'Chitrakoot' },
        { name: 'Deoria',value:'Deoria' },
        { name: 'Etah',value:'Etah' },
        { name: 'Etawah',value:'Etawah' },
        { name: 'Faizabad',value:'Faizabad' },
        { name: 'Farrukhabad',value:'Farrukhabad' },
        { name: 'Fatehpur',value:'Fatehpur' },
        { name: 'Firozabad',value:'Firozabad' },
        { name: 'Gautam Buddha Nagar',value:'Gautam Buddha Nagar' },
        { name: 'Ghaziabad',value:'Ghaziabad' },
        { name: 'Ghazipur',value:'Ghazipur' },
        { name: 'Gonda',value:'Gonda' },
        { name: 'Gorakhpur',value:'Gorakhpur' },
        { name: 'Hamirpur',value:'Hamirpur' },
        { name: 'Hapur',value:'Hapur' },
        { name: 'Hardoi',value:'Hardoi' },
        { name: 'Hathras',value:'Hathras' },
        { name: 'Jalaun',value:'Jalaun' },
        { name: 'Jaunpur',value:'Jaunpur' },
        { name: 'Jhansi',value:'Jhansi' },
        { name: 'Kannauj',value:'Kannauj' },
        { name: 'Kanpur Dehat',value:'Kanpur Dehat' },
        { name: 'Kanpur Nagar',value:'Kanpur Nagar' },
        { name: 'Kanshiram Nagar',value:'Kanshiram Nagar' },
        { name: 'Kaushambi',value:'Kaushambi' },
        { name: 'Kushinagar',value:'Kushinagar' },
        { name: 'Lakhimpur Kheri',value:'Lakhimpur Kheri' },
        { name: 'Lalitpur',value:'Lalitpur' },
        { name: 'Lucknow',value:'Lucknow' },
        { name: 'Maharajganj',value:'Maharajganj' },
        { name: 'Mahoba',value:'Mahoba' },
        { name: 'Mainpuri',value:'Mainpuri' },
        { name: 'Mathura',value:'Mathura' },
        { name: 'Mau',value:'Mau' },
        { name: 'Meerut',value:'Meerut' },
        { name: 'Mirzapur',value:'Mirzapur' },
        { name: 'Moradabad',value:'Moradabad' },
        { name: 'Muzaffarnagar',value:'Muzaffarnagar' },
        { name: 'Pilibhit',value:'Pilibhit' },
        { name: 'Pratapgarh',value:'Pratapgarh' },
        { name: 'Raebareli',value:'Raebareli' },
        { name: 'Rampur',value:'Rampur' },
        { name: 'Saharanpur',value:'Saharanpur' },
        { name: 'Sambhal',value:'Sambhal' },
        { name: 'Sant Kabir Nagar',value:'Sant Kabir Nagar' },
        { name: 'Shahjahanpur',value:'Shahjahanpur' },
        { name: 'Shamli',value:'Shamli' },
        { name: 'Shravasti',value:'Shravasti' },
        { name: 'Siddharthnagar',value:'Siddharthnagar' },
        { name: 'Sitapur',value:'Sitapur' },
        { name: 'Sonbhadra',value:'Sonbhadra' },
        { name: 'Sultanpur',value:'Sultanpur' },
        { name: 'Unnao',value:'Unnao' },
        { name: 'Varanasi',value:'Varanasi' },
        
        
             
            ]
          },
          {
            name: 'Uttarakhand',
            cities: [
              { name: 'Almora',value:'Almora' },
        { name: 'Bageshwar',value:'Bageshwar' },
        { name: 'Chamoli',value:'Chamoli' },
        { name: 'Champawat',value:'Champawat' },
        { name: 'Dehradun',value:'Dehradun' },
        { name: 'Haridwar',value:'Haridwar' },
        { name: 'Nainital',value:'Nainital' },
        { name: 'Pauri Garhwal',value:'Pauri Garhwal' },
        { name: 'Pithoragarh',value:'Pithoragarh' },
        { name: 'Rudraprayag',value:'Rudraprayag' },
        { name: 'Tehri Garhwal',value:'Tehri Garhwal' },
        { name: 'Udham Singh Nagar',value:'Udham Singh Nagar' },
        { name: 'Uttarkashi',value:'Uttarkashi' },
        
        
        
             
            ]
          },{
            name: 'West Bengal',
            cities: [
              { name: 'Alipurduar',value:'Alipurduar' },
        { name: 'Bankura',value:'Bankura' },
        { name: 'Birbhum',value:'Birbhum' },
        { name: 'Cooch Behar',value:'Cooch Behar' },
        { name: 'Dakshin Dinajpur',value:'Dakshin Dinajpur' },
        { name: 'Darjeeling',value:'Darjeeling' },
        { name: 'Hooghly',value:'Hooghly' },
        { name: 'Howrah',value:'Howrah' },
        { name: 'Jalpaiguri',value:'Jalpaiguri' },
        { name: 'Jhargram',value:'Jhargram' },
        { name: 'Kalimpong',value:'Kalimpong' },
        { name: 'Kolkata',value:'Kolkata' },
        { name: 'Malda',value:'Malda' },
        { name: 'Murshidabad',value:'Murshidabad' },
        { name: 'Nadia',value:'Nadia' },
        { name: 'North 24 Parganas',value:'North 24 Parganas' },
        { name: 'Paschim Bardhaman',value:'Paschim Bardhaman' },
        { name: 'Paschim Medinipur',value:'Paschim Medinipur' },
        { name: 'Purba Bardhaman',value:'Purba Bardhaman' },
        { name: 'Yadgir',value:'Yadgir' },
        { name: 'Uttara Kannada',value:'Uttara Kannada' },
        { name: 'Vijayapura',value:'Vijayapura' },
        { name: 'Yadgir',value:'Yadgir' },
        
        
             
            ]
          },{
            name: 'Andaman and Nicobar Islands',
            cities: [
              { name: 'Nicobar',value:'Nicobar' },
        { name: 'North and Middle Andaman',value:'North and Middle Andaman' },
        { name: 'South Andaman',value:'South Andaman' },
        
             
            ]
          },
          {
            name: 'Chandigarh',
            cities: [
              { name: 'Chandigarh',value:'Chandigarh' },
        
             
            ]
          },
          {
            name: 'Dadra and Nagar Haveli and Daman and Diu',
        
            cities: [
              { name: 'Dadra and Nagar Haveli',value:'Dadra and Nagar Haveli' },
        { name: 'Daman',value:'Daman' },
        { name: 'Diu',value:'Diu' },
        
             
            ]
          },
          {
            name: 'Lakshadweep',
            cities: [
              { name: 'Lakshadweep',value:'Lakshadweep' },
             
            ]
          },
          {
            name: 'Delhi',
            cities: [
              { name: 'Central Delhi',value:'Central Delhi' },
        { name: 'East Delhi',value:'East Delhi' },
        { name: 'New Delhi',value:'New Delhi' },
        { name: 'North Delhi',value:'North Delhi' },
        { name: 'North East Delhi',value:'North East Delhi' },
        { name: 'North West Delhi',value:'North West Delhi' },
        { name: 'Shahdara',value:'Shahdara' },
        { name: 'South Delhi',value:'South Delhi' },
        { name: 'South East Delhi',value:'South East Delhi' },
        { name: 'South West Delhi',value:'South West Delhi' },
        { name: 'West Delhi',value:'West Delhi' },
        
             
            ]
          },
          {
            name: 'Pondicherry',
            cities: [
              { name: 'Puducherry',value:'Puducherry' },
        { name: 'Karaikal',value:'Karaikal' },
        { name: 'Mahe',value:'Mahe' },
        { name: 'Yanam',value:'Yanam' },
        
             
            ]
          },
          {
            name: 'Jammu and Kashmir',
            cities: [
              { name: 'Anantnag',value:'Anantnag' },
        { name: 'Bandipora',value:'Bandipora' },
        { name: 'Baramulla',value:'Baramulla' },
        { name: 'Budgam',value:'Budgam' },
        { name: 'Doda',value:'Doda' },
        { name: 'Ganderbal',value:'Ganderbal' },
        { name: 'Jammu',value:'Jammu' },
        { name: 'Kathua',value:'Kathua' },
        { name: 'Kishtwar',value:'Kishtwar' },
        { name: 'Kulgam',value:'Kulgam' },
        { name: 'Kupwara',value:'Kupwara' },
        { name: 'Leh',value:'Leh' },
        { name: 'Poonch',value:'Poonch' },
        { name: 'Pulwama',value:'Pulwama' },
        { name: 'Rajouri',value:'Rajouri' },
        { name: 'Ramban',value:'Ramban' },
        { name: 'Reasi',value:'Reasi' },
        { name: 'Samba',value:'Samba' },
        { name: 'Shopian',value:'Shopian' },
        { name: 'Srinagar',value:'Srinagar' },
        
        
             
            ]
          },
          {
            name: 'Ladakh',
            cities: [
              { name: 'Kargil',value:'Kargil' },
        { name: 'Leh',value:'Leh' },
        
        
             
            ]
          },
          // Add more states and their cities as needed
        ];
        
        this.ugdegrees = [
          { name: 'Bachelor of Arts (BA)', value:'Bachelor of Arts (BA)' },
 { name: 'Bachelor of Science (BSc)', value:'Bachelor of Science (BSc)' },
 { name: 'Bachelor of Commerce (BCom)', value:'Bachelor of Commerce (BCom)' },
 { name: 'Bachelor of Engineering (BE)', value:'Bachelor of Engineering (BE)' },
 { name: 'Bachelor of Technology (B.Tech)', value:'Bachelor of Technology (B.Tech)' },
 { name: 'Bachelor of Business Administration (BBA)', value:'Bachelor of Business Administration (BBA)' },
 { name: 'Bachelor of Computer Applications (BCA)', value:'Bachelor of Computer Applications (BCA)' },
 { name: 'Bachelor of Architecture (BArch)', value:'Bachelor of Architecture (BArch)' },
 { name: 'Bachelor of Education (B.Ed)', value:'Bachelor of Education (B.Ed)' },
 { name: 'Bachelor of Pharmacy (B.Pharm)', value:'Bachelor of Pharmacy (B.Pharm)' },
 { name: 'Bachelor of Dental Surgery (BDS)', value:'Bachelor of Dental Surgery (BDS)' },
 { name: 'Bachelor of Medicine and Bachelor of Surgery (MBBS)', value:'Bachelor of Medicine and Bachelor of Surgery (MBBS)' },
 { name: 'Bachelor of Ayurvedic Medicine and Surgery (BAMS)', value:'Bachelor of Ayurvedic Medicine and Surgery (BAMS)' },
 { name: 'Bachelor of Homeopathic Medicine and Surgery (BHMS)', value:'Bachelor of Homeopathic Medicine and Surgery (BHMS)' },
 { name: 'Bachelor of Unani Medicine and Surgery (BUMS)', value:'Bachelor of Unani Medicine and Surgery (BUMS)' },
 { name: 'Bachelor of Science in Nursing (BSc Nursing)', value:'Bachelor of Science in Nursing (BSc Nursing)' },
 { name: 'Bachelor of Physiotherapy (BPT)', value:'Bachelor of Physiotherapy (BPT)' },
 { name: 'Bachelor of Occupational Therapy (BOT)', value:'Bachelor of Occupational Therapy (BOT)' },
 { name: 'Bachelor of Optometry (B.Optom)', value:'Bachelor of Optometry (B.Optom)' },
 { name: 'Bachelor of Veterinary Science and Animal Husbandry (B.VSc & AH)', value:'Bachelor of Veterinary Science and Animal Husbandry (B.VSc & AH)' },
 { name: 'Bachelor of Fisheries Science (B.FSc)', value:'Bachelor of Fisheries Science (B.FSc)' },
 { name: 'Bachelor of Fine Arts (BFA)', value:'Bachelor of Fine Arts (BFA)' },
 { name: 'Bachelor of Journalism and Mass Communication (BJMC)', value:'Bachelor of Journalism and Mass Communication (BJMC)' },
 { name: 'Bachelor of Design (B.Des)', value:'Bachelor of Design (B.Des)' },
 { name: 'Bachelor of Law (LLB)', value:'Bachelor of Law (LLB)' },
 { name: 'Bachelor of Arts and Bachelor of Law (BA LLB)', value:'Bachelor of Arts and Bachelor of Law (BA LLB)' },
 { name: 'Bachelor of Business Administration and Bachelor of Law (BBA LLB)', value:'Bachelor of Business Administration and Bachelor of Law (BBA LLB)' },
 { name: 'Bachelor of Hotel Management and Catering Technology (BHMCT)', value:'Bachelor of Hotel Management and Catering Technology (BHMCT)' },
 { name: 'Bachelor of Travel and Tourism Management (BTTM)', value:'Bachelor of Travel and Tourism Management (BTTM)' },
 { name: 'Bachelor of Event Management (BEM)', value:'Bachelor of Event Management (BEM)' },
 { name: 'Bachelor of Mass Media and Communication (BMMC)', value:'Bachelor of Mass Media and Communication (BMMC)' },
 { name: 'Bachelor of Library and Information Science (BLISc)', value:'Bachelor of Library and Information Science (BLISc)' },
 { name: 'Bachelor of Social Work (BSW)', value:'Bachelor of Social Work (BSW)' },
 { name: 'Bachelor of Physical Education (BPEd)', value:'Bachelor of Physical Education (BPEd)' },
 { name: 'Bachelor of Performing Arts (BPA)', value:'Bachelor of Performing Arts (BPA)' },
 { name: 'Bachelor of Film and Television Production (BFTP)', value:'Bachelor of Film and Television Production (BFTP)' },
 { name: 'Bachelor of Animation and Multimedia (BAM)', value:'Bachelor of Animation and Multimedia (BAM)' },
 { name: 'Bachelor of Graphic Design (BGD)', value:'Bachelor of Graphic Design (BGD)' },
 { name: 'Bachelor of Photography (BPhot)', value:'Bachelor of Photography (BPhot)' },
 { name: 'Bachelor of Music (BMus)', value:'Bachelor of Music (BMus)' },
 { name: 'Bachelor of Theatre Arts (BTA)', value:'Bachelor of Theatre Arts (BTA)' },
 { name: 'Bachelor of Philosophy (BPhilo)', value:'Bachelor of Philosophy (BPhilo)' },
 { name: 'Bachelor of Psychology (BPsych)', value:'Bachelor of Psychology (BPsych)' },
 { name: 'Bachelor of Economics (BEcon)', value:'Bachelor of Economics (BEcon)' },
 { name: 'Bachelor of Business Economics (BBE)', value:'Bachelor of Business Economics (BBE)' },
 { name: 'Bachelor of Commerce (BC)', value:'Bachelor of Commerce (BC)' },
        ];

        this.pgdegrees=[
          { name: 'Master of Arts (MA)', value:'Master of Arts (MA)' },
 { name: 'Master of Science (MSc)', value:'Master of Science (MSc)' },
 { name: 'Master of Commerce (MCom)', value:'Master of Commerce (MCom)' },
 { name: 'Master of Business Administration (MBA)', value:'Master of Business Administration (MBA)' },
 { name: 'Master of Computer Applications (MCA)', value:'Master of Computer Applications (MCA)' },
 { name: 'Master of Engineering (MEng)', value:'Master of Engineering (MEng)' },
 { name: 'Master of Technology (MTech)', value:'Master of Technology (MTech)' },
 { name: 'Master of Architecture (MArch)', value:'Master of Architecture (MArch)' },
 { name: 'Master of Planning (MPlan)', value:'Master of Planning (MPlan)' },
 { name: 'Master of Laws (LLM)', value:'Master of Laws (LLM)' },
 { name: 'Master of Education (MEd)', value:'Master of Education (MEd)' },
 { name: 'Master of Physical Education (MPEd)', value:'Master of Physical Education (MPEd)' },
 { name: 'Master of Fine Arts (MFA)', value:'Master of Fine Arts (MFA)' },
 { name: 'Master of Design (MDes)', value:'Master of Design (MDes)' },
 { name: 'Master of Journalism and Mass Communication (MJMC)', value:'Master of Journalism and Mass Communication (MJMC)' },
 { name: 'Master of Library and Information Science (MLISc)', value:'Master of Library and Information Science (MLISc)' },
 { name: 'Master of Social Work (MSW)', value:'Master of Social Work (MSW)' },
 { name: 'Master of Public Health (MPH)', value:'Master of Public Health (MPH)' },
 { name: 'Master of Hospital Administration (MHA)', value:'Master of Hospital Administration (MHA)' },
 { name: 'Master of Pharmacy (MPharm)', value:'Master of Pharmacy (MPharm)' },
 { name: 'Master of Dental Surgery (MDS)', value:'Master of Dental Surgery (MDS)' },
 { name: 'Master of Ayurvedic Medicine and Surgery (MAMS)', value:'Master of Ayurvedic Medicine and Surgery (MAMS)' },
 { name: 'Master of Homeopathic Medicine and Surgery (MHMS)', value:'Master of Homeopathic Medicine and Surgery (MHMS)' },
 { name: 'Master of Unani Medicine and Surgery (MUMS)', value:'Master of Unani Medicine and Surgery (MUMS)' },
 { name: 'Master of Siddha Medicine (MSidd)', value:'Master of Siddha Medicine (MSidd)' },
 { name: 'Master of Naturopathy and Yogic Science (MNYSc)', value:'Master of Naturopathy and Yogic Science (MNYSc)' },
        ];

        this.years = [  { name:'Less than 1 year', value:'Less than 1 year'},  
        { name:'1 year', value:'1 year'},  { name:'2 years', value:'2 years'},  
        { name:'3 years', value:'3 years'},  { name:'4 years', value:'4 years'},  
        { name:'5 years', value:'5 years'},  { name:'6 years', value:'6 years'},  
        { name:'7 years', value:'7 years'},  { name:'8 years', value:'8 years'},  
        { name:'9 years', value:'9 years'},  { name:'10 years', value:'10 years'},  
        { name:'11 years', value:'11 years'},  { name:'12 years', value:'12 years'},  
        { name:'13 years', value:'13 years'},  { name:'14 years', value:'14 years'},  
        { name:'15 years', value:'15 years'},  { name:'16 years', value:'16 years'},  
        { name:'17 years', value:'17 years'},  { name:'18 years', value:'18 years'},  
        { name:'19 years', value:'19 years'},  { name:'20 years', value:'20 years'},  
        { name:'21 years', value:'21 years'},  { name:'22 years', value:'22 years'}, 
        { name:'23 years', value:'23 years'},  { name:'24 years', value:'24 years'},  
        { name:'25 years', value:'25 years'},  { name:'26 years', value:'26 years'},  
        { name:'27 years', value:'27 years'},  { name:'28 years', value:'28 years'},  
        { name:'29 years', value:'29 years'},  { name:'30 years or more', value:'30 years or more'}];

        this.salary = [{ name: '0.5 LPA', value:'0.5 LPA' },
        { name: '1 LPA', value:'1 LPA' },
        { name: '1.5 LPA', value:'1.5 LPA' },
        { name: '2 LPA', value:'2 LPA' },
        { name: '2.5 LPA', value:'2.5 LPA' },
        { name: '3 LPA', value:'3 LPA' },
        { name: '3.5 LPA', value:'3.5 LPA' },
        { name: '4 LPA', value:'4 LPA' },
        { name: '4.5 LPA', value:'4.5 LPA' },
        { name: '5 LPA', value:'5 LPA' },
        { name: '5.5 LPA', value:'5.5 LPA' },
        { name: '6 LPA', value:'6 LPA' },
        { name: '6.5 LPA', value:'6.5 LPA' },
        { name: '7 LPA', value:'7 LPA' },
        { name: '7.5 LPA', value:'7.5 LPA' },
        { name: '8 LPA', value:'8 LPA' },
        { name: '8.5 LPA', value:'8.5 LPA' },
        { name: '9 LPA', value:'9 LPA' },
        { name: '9.5 LPA', value:'9.5 LPA' },
        { name: '10 LPA', value:'10 LPA' },
        { name: '10.5 LPA', value:'10.5 LPA' },
        { name: '11 LPA', value:'11 LPA' },
        { name: '11.5 LPA', value:'11.5 LPA' },
        { name: '12 LPA', value:'12 LPA' },
        { name: '12.5 LPA', value:'12.5 LPA' },
        { name: '13 LPA', value:'13 LPA' },
        { name: '13.5 LPA', value:'13.5 LPA' },
        { name: '14 LPA', value:'14 LPA' },
        { name: '14.5 LPA', value:'14.5 LPA' },
        { name: '15 LPA', value:'15 LPA' },
        { name: '15.5 LPA', value:'15.5 LPA' },
        { name: '16 LPA', value:'16 LPA' },
        { name: '16.5 LPA', value:'16.5 LPA' },
        { name: '17 LPA', value:'17 LPA' },
        { name: '17.5 LPA', value:'17.5 LPA' },
        { name: '18 LPA', value:'18 LPA' },
        { name: '18.5 LPA', value:'18.5 LPA' },
        { name: '19 LPA', value:'19 LPA' },
        { name: '19.5 LPA', value:'19.5 LPA' },
        { name: '20 LPA', value:'20 LPA' },
        { name: '20.5 LPA', value:'20.5 LPA' },
        { name: '21 LPA', value:'21 LPA' },
        { name: '21.5 LPA', value:'21.5 LPA' },
        { name: '22 LPA', value:'22 LPA' },
        { name: '22.5 LPA', value:'22.5 LPA' },
        { name: '23 LPA', value:'23 LPA' },
        { name: '23.5 LPA', value:'23.5 LPA' },
        { name: '24 LPA', value:'24 LPA' },
        { name: '24.5 LPA', value:'24.5 LPA' },
        { name: '25 LPA', value:'25 LPA' },
        { name: '25.5 LPA', value:'25.5 LPA' },
        { name: '26 LPA', value:'26 LPA' },
        { name: '26.5 LPA', value:'26.5 LPA' },
        { name: '27 LPA', value:'27 LPA' },
        { name: '27.5 LPA', value:'27.5 LPA' },
        { name: '28 LPA', value:'28 LPA' },
        { name: '28.5 LPA', value:'28.5 LPA' },
        { name: '29 LPA', value:'29 LPA' },
        { name: '29.5 LPA', value:'29.5 LPA' },
        { name: '30 LPA', value:'30 LPA' },
        { name: '30.5 LPA', value:'30.5 LPA' },
        { name: '31 LPA', value:'31 LPA' },
        { name: '31.5 LPA', value:'31.5 LPA' },
        { name: '32 LPA', value:'32 LPA' },
        { name: '32.5 LPA', value:'32.5 LPA' },
        { name: '33 LPA', value:'33 LPA' },
        { name: '33.5 LPA', value:'33.5 LPA' },
        { name: '34 LPA', value:'34 LPA' },
        { name: '34.5 LPA', value:'34.5 LPA' },
        { name: '35 LPA', value:'35 LPA' },
        { name: '35.5 LPA', value:'35.5 LPA' },
        { name: '36 LPA', value:'36 LPA' },
        { name: '36.5 LPA', value:'36.5 LPA' },
        { name: '37 LPA', value:'37 LPA' },
        { name: '37.5 LPA', value:'37.5 LPA' },
        { name: '38 LPA', value:'38 LPA' },
        { name: '38.5 LPA', value:'38.5 LPA' },
        { name: '39 LPA', value:'39 LPA' },
        { name: '39.5 LPA', value:'39.5 LPA' },
        { name: '40 LPA', value:'40 LPA' },
        { name: '40.5 LPA', value:'40.5 LPA' },
        { name: '41 LPA', value:'41 LPA' },
        { name: '41.5 LPA', value:'41.5 LPA' },
        { name: '42 LPA', value:'42 LPA' },
        { name: '42.5 LPA', value:'42.5 LPA' },
        { name: '43 LPA', value:'43 LPA' },
        { name: '43.5 LPA', value:'43.5 LPA' },
        { name: '44 LPA', value:'44 LPA' },
        { name: '44.5 LPA', value:'44.5 LPA' },
        { name: '45 LPA', value:'45 LPA' },
        { name: '45.5 LPA', value:'45.5 LPA' },
        { name: '46 LPA', value:'46 LPA' },
        { name: '46.5 LPA', value:'46.5 LPA' },
        { name: '47 LPA', value:'47 LPA' },
        { name: '47.5 LPA', value:'47.5 LPA' },
        { name: '48 LPA', value:'48 LPA' },
        { name: '48.5 LPA', value:'48.5 LPA' },
        { name: '49 LPA', value:'49 LPA' },
        { name: '49.5 LPA', value:'49.5 LPA' },
        { name: '50 LPA', value:'50 LPA' },
        { name: '50.5 LPA', value:'50.5 LPA' },
        { name: '51 LPA', value:'51 LPA' },
        { name: '51.5 LPA', value:'51.5 LPA' },
        { name: '52 LPA', value:'52 LPA' },
        { name: '52.5 LPA', value:'52.5 LPA' },
        { name: '53 LPA', value:'53 LPA' },
        { name: '53.5 LPA', value:'53.5 LPA' },
        { name: '54 LPA', value:'54 LPA' },
        { name: '54.5 LPA', value:'54.5 LPA' },
        { name: '55 LPA', value:'55 LPA' },
        { name: '55.5 LPA', value:'55.5 LPA' },
        { name: '56 LPA', value:'56 LPA' },
        { name: '56.5 LPA', value:'56.5 LPA' },
        { name: '57 LPA', value:'57 LPA' },
        { name: '57.5 LPA', value:'57.5 LPA' },
        { name: '58 LPA', value:'58 LPA' },
        { name: '58.5 LPA', value:'58.5 LPA' },
        { name: '59 LPA', value:'59 LPA' },
        { name: '59.5 LPA', value:'59.5 LPA' },
        { name: '60 LPA', value:'60 LPA' },
        { name: '60.5 LPA', value:'60.5 LPA' },
        { name: '61 LPA', value:'61 LPA' },
        { name: '61.5 LPA', value:'61.5 LPA' },
        { name: '62 LPA', value:'62 LPA' },
        { name: '62.5 LPA', value:'62.5 LPA' },
        { name: '63 LPA', value:'63 LPA' },
        { name: '63.5 LPA', value:'63.5 LPA' },
        { name: '64 LPA', value:'64 LPA' },
        { name: '64.5 LPA', value:'64.5 LPA' },
        { name: '65 LPA', value:'65 LPA' },
        { name: '65.5 LPA', value:'65.5 LPA' },
        { name: '66 LPA', value:'66 LPA' },
        { name: '66.5 LPA', value:'66.5 LPA' },
        { name: '67 LPA', value:'67 LPA' },
        { name: '67.5 LPA', value:'67.5 LPA' },
        { name: '68 LPA', value:'68 LPA' },
        { name: '68.5 LPA', value:'68.5 LPA' },
        { name: '69 LPA', value:'69 LPA' },
        { name: '69.5 LPA', value:'69.5 LPA' },
        { name: '70 LPA', value:'70 LPA' },
        { name: '70.5 LPA', value:'70.5 LPA' },
        { name: '71 LPA', value:'71 LPA' },
        { name: '71.5 LPA', value:'71.5 LPA' },
        { name: '72 LPA', value:'72 LPA' },
        { name: '72.5 LPA', value:'72.5 LPA' },
        { name: '73 LPA', value:'73 LPA' },
        { name: '73.5 LPA', value:'73.5 LPA' },
        { name: '74 LPA', value:'74 LPA' },
        { name: '74.5 LPA', value:'74.5 LPA' },
        { name: '75 LPA', value:'75 LPA' },
        { name: '75.5 LPA', value:'75.5 LPA' },
        { name: '76 LPA', value:'76 LPA' },
        { name: '76.5 LPA', value:'76.5 LPA' },
        { name: '77 LPA', value:'77 LPA' },
        { name: '77.5 LPA', value:'77.5 LPA' },
        { name: '78 LPA', value:'78 LPA' },
        { name: '78.5 LPA', value:'78.5 LPA' },
        { name: '79 LPA', value:'79 LPA' },
        { name: '79.5 LPA', value:'79.5 LPA' },
        { name: '80 LPA', value:'80 LPA' },
        { name: '80.5 LPA', value:'80.5 LPA' },
        { name: '81 LPA', value:'81 LPA' },
        { name: '81.5 LPA', value:'81.5 LPA' },
        { name: '82 LPA', value:'82 LPA' },
        { name: '82.5 LPA', value:'82.5 LPA' },
        { name: '83 LPA', value:'83 LPA' },
        { name: '83.5 LPA', value:'83.5 LPA' },
        { name: '84 LPA', value:'84 LPA' },
        { name: '84.5 LPA', value:'84.5 LPA' },
        { name: '85 LPA', value:'85 LPA' },
        { name: '85.5 LPA', value:'85.5 LPA' },
        { name: '86 LPA', value:'86 LPA' },
        { name: '86.5 LPA', value:'86.5 LPA' },
        { name: '87 LPA', value:'87 LPA' },
        { name: '87.5 LPA', value:'87.5 LPA' },
        { name: '88 LPA', value:'88 LPA' },
        { name: '88.5 LPA', value:'88.5 LPA' },
        { name: '89 LPA', value:'89 LPA' },
        { name: '89.5 LPA', value:'89.5 LPA' },
        { name: '90 LPA', value:'90 LPA' },
        { name: '90.5 LPA', value:'90.5 LPA' },
        { name: '91 LPA', value:'91 LPA' },
        { name: '91.5 LPA', value:'91.5 LPA' },
        { name: '92 LPA', value:'92 LPA' },
        { name: '92.5 LPA', value:'92.5 LPA' },
        { name: '93 LPA', value:'93 LPA' },
        { name: '93.5 LPA', value:'93.5 LPA' },
        { name: '94 LPA', value:'94 LPA' },
        { name: '94.5 LPA', value:'94.5 LPA' },
        { name: '95 LPA', value:'95 LPA' },
        { name: '95.5 LPA', value:'95.5 LPA' },
        { name: '96 LPA', value:'96 LPA' },
        { name: '96.5 LPA', value:'96.5 LPA' },
        { name: '97 LPA', value:'97 LPA' },
        { name: '97.5 LPA', value:'97.5 LPA' },
        { name: '98 LPA', value:'98 LPA' },
        { name: '98.5 LPA', value:'98.5 LPA' },
        { name: '99 LPA', value:'99 LPA' },
        { name: '99.5 LPA', value:'99.5 LPA' },
        { name: '100 LPA', value:'100 LPA' },];

        this.role= [
          { name: 'Admin Big Data', value:'Admin Big Data' },
          { name: 'Ansible Operations Engineer', value:'Ansible Operations Engineer' },
          { name: 'Artifactory Administrator', value:'Artifactory Administrator' },
          { name: 'Artificial Intelligence / Machine Learning Engineer', value:'Artificial Intelligence / Machine Learning Engineer' },
          { name: 'Artificial Intelligence / Machine Learning Leader', value:'Artificial Intelligence / Machine Learning Leader' },
          { name: 'Artificial Intelligence / Machine Learning Sr.Leader', value:'Artificial Intelligence / Machine Learning Sr.Leader' },
          { name: 'Artificial Intelligence Architect', value:'Artificial Intelligence Architect' },
          { name: 'Artificial Intelligence Researcher', value:'Artificial Intelligence Researcher' },
          { name: 'Big Data Architect', value:'Big Data Architect' },
          { name: 'Big Data Engineer', value:'Big Data Engineer' },
          { name: 'Big Data Specialist', value:'Big Data Specialist' },
          { name: 'Build And Release Engineer', value:'Build And Release Engineer' },
          { name: 'Build Engineer', value:'Build Engineer' },
          { name: 'Chef Operations Engineer', value:'Chef Operations Engineer' },
          { name: 'Data Analysts', value:'Data Analysts' },
          { name: 'Data Architect', value:'Data Architect' },
          { name: 'Devops Architect', value:'Devops Architect' },
          { name: 'Devops Engineer', value:'Devops Engineer' },
          { name: 'Elk Engineer', value:'Elk Engineer' },
          { name: 'Gerrit Administrator', value:'Gerrit Administrator' },
          { name: 'Jenkins Engineer', value:'Jenkins Engineer' },
          { name: 'Jira Administrator', value:'Jira Administrator' },
          { name: 'Kubernetes Operations Engineer', value:'Kubernetes Operations Engineer' },
          { name: 'Machine Learning Architect', value:'Machine Learning Architect' },
          { name: 'Machine Learning Engineer', value:'Machine Learning Engineer' },
          { name: 'Operations Engineer', value:'Operations Engineer' },
          { name: 'Principle Engineer In Artificial Intelligence', value:'Principle Engineer In Artificial Intelligence' },
          { name: 'Principle Engineer In Big Data', value:'Principle Engineer In Big Data' },
          { name: 'Principle Engineer In Data Analysis', value:'Principle Engineer In Data Analysis' },
          { name: 'Principle Engineer In Machine Learning', value:'Principle Engineer In Machine Learning' },
          { name: 'Production Support Engineer', value:'Production Support Engineer' },
          { name: 'Puppet Operations Engineer', value:'Puppet Operations Engineer' },
          { name: 'Senior Build And Release Engineer', value:'Senior Build And Release Engineer' },
          { name: 'Senior Build Engineer', value:'Senior Build Engineer' },
          { name: 'Senior Devops Engineer', value:'Senior Devops Engineer' },
          { name: 'Senior Site Reliability Engineer', value:'Senior Site Reliability Engineer' },
          { name: 'Site Reliability Engineer (Kubernetes – Docker)', value:'Site Reliability Engineer (Kubernetes – Docker)' },
          { name: 'Splunk Engineer', value:'Splunk Engineer' },
          { name: 'Dot Net Developer', value:'Dot Net Developer' },
          { name: 'Accessibility Specialist', value:'Accessibility Specialist' },
          { name: 'Agile Project Manager', value:'Agile Project Manager' },
          { name: 'Android Developer', value:'Android Developer' },
          { name: 'Ansible Automation Engineer', value:'Ansible Automation Engineer' },
          { name: 'Appdynamics Engineer', value:'Appdynamics Engineer' },
          { name: 'Application Security Engineer', value:'Application Security Engineer' },
          { name: 'Artifactory Engineer', value:'Artifactory Engineer' },
          { name: 'Artificial Intelligence (Ai) / Machine Learning Engineer', value:'Artificial Intelligence (Ai) / Machine Learning Engineer' },
          { name: 'Aws Devops Engineer', value:'Aws Devops Engineer' },
          { name: 'Aws Solutions Architect', value:'Aws Solutions Architect' },
          { name: 'Azure Devops Engineer', value:'Azure Devops Engineer' },
          { name: 'Bamboo Engineer', value:'Bamboo Engineer' },
          { name: 'Bitbucket Engineer', value:'Bitbucket Engineer' },
          { name: 'Blockchain Developer', value:'Blockchain Developer' },
          { name: 'Business Systems Analyst', value:'Business Systems Analyst' },
          { name: 'C# Developer', value:'C# Developer' },
          { name: 'Chef Inspec Engineer', value:'Chef Inspec Engineer' },
          { name: 'Cloud Administrator', value:'Cloud Administrator' },
          { name: 'Cloud Architect', value:'Cloud Architect' },
          { name: 'Cloud Automation Engineer', value:'Cloud Automation Engineer' },
          { name: 'Cloud Engineer', value:'Cloud Engineer' },
          { name: 'Cloud Network Engineer', value:'Cloud Network Engineer' },
          { name: 'Cloud Security Engineer', value:'Cloud Security Engineer' },
          { name: 'Cnc Programmer', value:'Cnc Programmer' },
          { name: 'Coder', value:'Coder' },
          { name: 'Computer Graphics Animator', value:'Computer Graphics Animator' },
          { name: 'Computer Hardware Engineer', value:'Computer Hardware Engineer' },
          { name: 'Computer Network Architect', value:'Computer Network Architect' },
          { name: 'Computer Programmer', value:'Computer Programmer' },
          { name: 'Computer Research Scientist', value:'Computer Research Scientist' },
          { name: 'Computer Systems Analyst', value:'Computer Systems Analyst' },
          { name: 'Confluence Engineer', value:'Confluence Engineer' },
          { name: 'Consul Engineer', value:'Consul Engineer' },
          { name: 'Coverage.Py Engineer', value:'Coverage.Py Engineer' },
          { name: 'Data Analyst', value:'Data Analyst' },
          { name: 'Data Engineer', value:'Data Engineer' },
          { name: 'Data Modeler', value:'Data Modeler' },
          { name: 'Data Scientist', value:'Data Scientist' },
          { name: 'Database Administrator', value:'Database Administrator' },
          { name: 'Datadog Engineer', value:'Datadog Engineer' },
          { name: 'Developer', value:'Developer' },
          { name: 'Devops Manager', value:'Devops Manager' },
          { name: 'Devsecops Architect', value:'Devsecops Architect' },
          { name: 'Devsecops Engineer', value:'Devsecops Engineer' },
          { name: 'Director Of Engineering', value:'Director Of Engineering' },
          { name: 'Docker Engineer', value:'Docker Engineer' },
          { name: 'Embedded Software Engineer', value:'Embedded Software Engineer' },
          { name: 'Entry Level Developer', value:'Entry Level Developer' },
          { name: 'Entry Level Network Engineer', value:'Entry Level Network Engineer' },
          { name: 'Entry Level Programmer', value:'Entry Level Programmer' },
          { name: 'Entry Level Software Developer', value:'Entry Level Software Developer' },
          { name: 'Entry Level Software Engineer', value:'Entry Level Software Engineer' },
          { name: 'Entry Level Web Developer', value:'Entry Level Web Developer' },
          { name: 'Envoy Engineer', value:'Envoy Engineer' },
          { name: 'Falco Engineer', value:'Falco Engineer' },
          { name: 'Fluentd Engineer', value:'Fluentd Engineer' },
          { name: 'Fortify Engineer', value:'Fortify Engineer' },
          { name: 'Frameworks Specialist', value:'Frameworks Specialist' },
          { name: 'Front End Developer', value:'Front End Developer' },
          { name: 'Front End Web Developer', value:'Front End Web Developer' },
          { name: 'Front-End Designer', value:'Front-End Designer' },
          { name: 'Front-End Developer', value:'Front-End Developer' },
          { name: 'Full Stack Developer', value:'Full Stack Developer' },
          { name: 'Full Stack Java Developer/Programmer/Engineer', value:'Full Stack Java Developer/Programmer/Engineer' },
          { name: 'Full Stack Python Developer/Programmer/Engineer', value:'Full Stack Python Developer/Programmer/Engineer' },
          { name: 'Full-Stack Developer', value:'Full-Stack Developer' },
          { name: 'Game Developer', value:'Game Developer' },
          { name: 'Gcp Devops Engineer', value:'Gcp Devops Engineer' },
          { name: 'Gerrit Engineer', value:'Gerrit Engineer' },
          { name: 'Git Engineer', value:'Git Engineer' },
          { name: 'Github Engineer', value:'Github Engineer' },
          { name: 'Gitlab Engineer', value:'Gitlab Engineer' },
          { name: 'Gradle Engineer', value:'Gradle Engineer' },
          { name: 'Grafana Engineer', value:'Grafana Engineer' },
          { name: 'Groovy Engineer', value:'Groovy Engineer' },
          { name: 'Information Architect', value:'Information Architect' },
          { name: 'Information Security Analyst', value:'Information Security Analyst' },
          { name: 'Interaction Designer', value:'Interaction Designer' },
          { name: 'Ios Developer', value:'Ios Developer' },
          { name: 'Istio Engineer', value:'Istio Engineer' },
          { name: 'It Manager', value:'It Manager' },
          { name: 'Jacoco Engineer', value:'Jacoco Engineer' },
          { name: 'Java Developer', value:'Java Developer' },
          { name: 'Javascript Developer', value:'Javascript Developer' },
          { name: 'Jira Engineer', value:'Jira Engineer' },
          { name: 'Jr Developer', value:'Jr Developer' },
          { name: 'Junior Developer', value:'Junior Developer' },
          { name: 'Junior Front End Developer', value:'Junior Front End Developer' },
          { name: 'Junior Ios Developer', value:'Junior Ios Developer' },
          { name: 'Junior Software Engineer', value:'Junior Software Engineer' },
          { name: 'Junior Web Developer', value:'Junior Web Developer' },
          { name: 'Junit Engineer', value:'Junit Engineer' },
          { name: 'Kubernetes Administrator', value:'Kubernetes Administrator' },
          { name: 'Kubernetes Engineer', value:'Kubernetes Engineer' },
          { name: 'Maven Engineer', value:'Maven Engineer' },
          { name: 'Micro Services / Api Lead Designer', value:'Micro Services / Api Lead Designer' },
          { name: 'Mobile App Developer', value:'Mobile App Developer' },
          { name: 'Mobile Application Developer', value:'Mobile Application Developer' },
          { name: 'Mobile Developer', value:'Mobile Developer' },
          { name: 'Mulesoft Developer', value:'Mulesoft Developer' },
          { name: 'Nagios Engineer', value:'Nagios Engineer' },
          { name: 'Network And Systems Administrator', value:'Network And Systems Administrator' },
          { name: 'Network Engineer', value:'Network Engineer' },
          { name: 'New Grad Software Engineer', value:'New Grad Software Engineer' },
          { name: 'New Relic Engineer', value:'New Relic Engineer' },
          { name: 'Nexus Engineer', value:'Nexus Engineer' },
          { name: 'Nomad Engineer', value:'Nomad Engineer' },
          { name: 'Notary Engineer', value:'Notary Engineer' },
          { name: 'Octopus Deploy Engineer', value:'Octopus Deploy Engineer' },
          { name: 'Openshift Engineer', value:'Openshift Engineer' },
          { name: 'Openstack Engineer', value:'Openstack Engineer' },
          { name: 'Oracle Developer', value:'Oracle Developer' },
          { name: 'Oracle Sql Developer', value:'Oracle Sql Developer' },
          { name: 'Packer Engineer', value:'Packer Engineer' },
          { name: 'Php Developer', value:'Php Developer' },
          { name: 'Powershell Engineer', value:'Powershell Engineer' },
          { name: 'Programmer', value:'Programmer' },
          { name: 'Programmer Analyst', value:'Programmer Analyst' },
          { name: 'Prometheus Engineer', value:'Prometheus Engineer' },
          { name: 'Puppet Engineer', value:'Puppet Engineer' },
          { name: 'Pytest Engineer', value:'Pytest Engineer' },
          { name: 'Python Developer', value:'Python Developer' },
          { name: 'Qa (Quality Assurance) Specialist', value:'Qa (Quality Assurance) Specialist' },
          { name: 'Qa Engineer', value:'Qa Engineer' },
          { name: 'React Developer', value:'React Developer' },
          { name: 'Robotics Engineer', value:'Robotics Engineer' },
          { name: 'Ruby On Rails Developer', value:'Ruby On Rails Developer' },
          { name: 'Salesforce Developer', value:'Salesforce Developer' },
          { name: 'Search Engine Optimization', value:'Search Engine Optimization' },
          { name: 'Security Specialist', value:'Security Specialist' },
          { name: 'Selenium Engineer', value:'Selenium Engineer' },
          { name: 'Senior Ansible Development Engineer', value:'Senior Ansible Development Engineer' },
          { name: 'Senior Cloud Architect', value:'Senior Cloud Architect' },
          { name: 'Senior Devops Architect', value:'Senior Devops Architect' },
          { name: 'Senior Devsecops Architect', value:'Senior Devsecops Architect' },
          { name: 'Senior Devsecops Engineer', value:'Senior Devsecops Engineer' },
          { name: 'Senior Sre Architect', value:'Senior Sre Architect' },
          { name: 'Senior Sre Engineer', value:'Senior Sre Engineer' },
          { name: 'Sharepoint Developer', value:'Sharepoint Developer' },
          { name: 'Software Developers', value:'Software Developers' },
          { name: 'Sonarqube Engineer', value:'Sonarqube Engineer' },
          { name: 'Splunk Enterprise Security Engineer', value:'Splunk Enterprise Security Engineer' },
          { name: 'Sql Developer', value:'Sql Developer' },
          { name: 'Sre Architect', value:'Sre Architect' },
          { name: 'Sre Engineer', value:'Sre Engineer' },
          { name: 'Systems Administrator', value:'Systems Administrator' },
          { name: 'Systems Engineer', value:'Systems Engineer' },
          { name: 'Teamcity Engineer', value:'Teamcity Engineer' },
          { name: 'Tech Sales Engineer', value:'Tech Sales Engineer' },
          { name: 'Technical Account Manager', value:'Technical Account Manager' },
          { name: 'Technical Lead', value:'Technical Lead' },
          { name: 'Terraform Engineer', value:'Terraform Engineer' },
          { name: 'Tfs Engineer', value:'Tfs Engineer' },
          { name: 'Twistkock Engineer', value:'Twistkock Engineer' },
          { name: 'Udeploy Engineer', value:'Udeploy Engineer' },
          { name: 'Ui Designer', value:'Ui Designer' },
          { name: 'Ui Developer', value:'Ui Developer' },
          { name: 'Unity Developer', value:'Unity Developer' },
          { name: 'Ux Designer', value:'Ux Designer' },
          { name: 'Vault Engineer', value:'Vault Engineer' },
          { name: 'Web Designer (Ui/Ux Designer)', value:'Web Designer (Ui/Ux Designer)' },
          { name: 'Web Developer', value:'Web Developer' },
          { name: 'Wordpress Developer', value:'Wordpress Developer' },
          { name: 'Xl Deploy Engineer', value:'Xl Deploy Engineer' },
          { name: 'Zabbix Engineer', value:'Zabbix Engineer' },
          { name: 'SEO Manager', value:'SEO Manager' },
          { name: 'SEO Engineer', value:'SEO Engineer' },
          { name: 'Digital Marketing Analyst', value:'Digital Marketing Analyst' },
          { name: 'Social Media Marketing Manager', value:'Social Media Marketing Manager' },
          { name: 'Social Media Marketing Analyst', value:'Social Media Marketing Analyst' },
          { name: 'MARKETING TECHNOLOGIST', value:'MARKETING TECHNOLOGIST' },
          { name: 'SEO CONSULTANT', value:'SEO CONSULTANT' },
          { name: 'WEB ANALYTICS DEVELOPER', value:'WEB ANALYTICS DEVELOPER' },
          { name: 'DIGITAL MARKETING MANAGER', value:'DIGITAL MARKETING MANAGER' },
          { name: 'SOCIAL MEDIA MANAGER', value:'SOCIAL MEDIA MANAGER' },
          { name: 'GROWTH HACKER', value:'GROWTH HACKER' },
          { name: 'CONTENT MANAGER', value:'CONTENT MANAGER' },
          { name: 'CONTENT STRATEGIST', value:'CONTENT STRATEGIST' },
          { name: 'HR Coordinator', value:'HR Coordinator' },
          { name: 'Payroll Coordinator', value:'Payroll Coordinator' },
          { name: 'Recruiting Coordinator', value:'Recruiting Coordinator' },
          { name: 'HR Specialist', value:'HR Specialist' },
          { name: 'HR Generalist', value:'HR Generalist' },
          { name: 'Recruiter', value:'Recruiter' },
          { name: 'Human Resource Information Specialist', value:'Human Resource Information Specialist' },
          { name: 'HR Manager', value:'HR Manager' },
          { name: 'Recruiting Manager', value:'Recruiting Manager' },
          { name: 'HR Business Partner', value:'HR Business Partner' },
          { name: 'HR Director', value:'HR Director' },
          { name: 'Recruiting Director', value:'Recruiting Director' },
          { name: 'VP of HR', value:'VP of HR' },
          { name: 'Chief Human Resource Officer', value:'Chief Human Resource Officer' },
          { name: 'Career Consultant', value:'Career Consultant' },
          { name: 'Career Advisor', value:'Career Advisor' },
          { name: 'Assignment Coordinator', value:'Assignment Coordinator' },
          { name: 'Placement Coordinator', value:'Placement Coordinator' },
          { name: 'Career Development Strategist', value:'Career Development Strategist' },
          { name: 'Personnel Agent', value:'Personnel Agent' },
          { name: 'Human Resources Officer', value:'Human Resources Officer' },
          { name: 'VP of Engineering', value:'VP of Engineering' },
          { name: 'Chief Architect', value:'Chief Architect' },
          { name: 'Software Architect', value:'Software Architect' },
          { name: 'Engineering Project Manager', value:'Engineering Project Manager' },
          { name: 'Engineering Manager', value:'Engineering Manager' },
          { name: 'Technical Project Manager', value:'Technical Project Manager' },
          { name: 'Project Manager', value:'Project Manager' },
          { name: 'Business Account Manager', value:'Business Account Manager' },
          { name: 'Senior Manager IT', value:'Senior Manager IT' },
          { name: 'IT Infra Manager', value:'IT Infra Manager' },
          { name: 'Procurement manager', value:'Procurement manager' },
          { name: 'Learning and Development Manager', value:'Learning and Development Manager' },
          { name: 'Learning and Development co-ordinators', value:'Learning and Development co-ordinators' },
          { name: 'CEO', value:'CEO' },
          { name: 'CTO', value:'CTO' },
          { name: 'CIO/Chief Digital Officer/Chief Innovation Officer', value:'CIO/Chief Digital Officer/Chief Innovation Officer' },
          { name: 'VP of Product Management/Head of Product', value:'VP of Product Management/Head of Product' },
          { name: 'Product Manager', value:'Product Manager' },
          { name: 'VP of Marketing', value:'VP of Marketing' },
          { name: 'VP of Engineering/Director of Engineering', value:'VP of Engineering/Director of Engineering' },
          { name: 'Engineering Project Manager/Engineering Manager', value:'Engineering Project Manager/Engineering Manager' },
          { name: 'Technical Lead/Engineering Lead/Team Lead', value:'Technical Lead/Engineering Lead/Team Lead' },
          { name: 'Principal Software Engineer', value:'Principal Software Engineer' },
          { name: 'Senior Software Engineer/Senior Software Developer', value:'Senior Software Engineer/Senior Software Developer' },
          { name: 'Software Engineer', value:'Software Engineer' },
          { name: 'Software Developer', value:'Software Developer' },
          { name: 'Junior Software Developer', value:'Junior Software Developer' },
          { name: 'Intern Software Developer', value:'Intern Software Developer' },
          { name: 'Application Developer', value:'Application Developer' },
          { name: 'Artificial Intelligence/Machine Learning Engineer', value:'Artificial Intelligence/Machine Learning Engineer' },
          { name: 'Back-end Developer', value:'Back-end Developer' },
          { name: 'Big Data Analyst', value:'Big Data Analyst' },
          { name: 'Business Analyst', value:'Business Analyst' },
          { name: 'Cloud Architect/Engineer', value:'Cloud Architect/Engineer' },
          { name: 'Computer Support Specialist', value:'Computer Support Specialist' },
          { name: 'Cybersecurity Analyst', value:'Cybersecurity Analyst' },
          { name: 'Enterprise Architect', value:'Enterprise Architect' },
          { name: 'Graphic Designer', value:'Graphic Designer' },
          { name: 'Help Desk Support', value:'Help Desk Support' },
          { name: 'IT Auditor', value:'IT Auditor' },
          { name: 'IT Consultant', value:'IT Consultant' },
          { name: 'IT Project Manager', value:'IT Project Manager' },
          { name: 'Linux Administrator', value:'Linux Administrator' },
          { name: 'Network Administrator', value:'Network Administrator' },
          { name: 'Operations Manager', value:'Operations Manager' },
          { name: 'Penetration Tester', value:'Penetration Tester' },
          { name: 'Program Manager', value:'Program Manager' },
          { name: 'Quality Assurance Analyst', value:'Quality Assurance Analyst' },
          { name: 'Salesforce Administrator', value:'Salesforce Administrator' },
          { name: 'Scrum Master', value:'Scrum Master' },
          { name: 'Security Engineer', value:'Security Engineer' },
          { name: 'SEO Specialist', value:'SEO Specialist' },
          { name: 'Solutions Architect', value:'Solutions Architect' },
          { name: 'System Administrator', value:'System Administrator' },
          { name: 'Systems Analyst', value:'Systems Analyst' },
          { name: 'Technical Writer', value:'Technical Writer' },
          { name: 'UI/UX Designer', value:'UI/UX Designer' },
          { name: 'Video Game Designer', value:'Video Game Designer' },
          { name: 'Virtual Reality Developer', value:'Virtual Reality Developer' },
          { name: 'Web Designer', value:'Web Designer' },
          { name: 'Windows Administrator', value:'Windows Administrator' },
          { name: 'Wireless Network Engineer', value:'Wireless Network Engineer' },
          { name: 'Business Intelligence Analyst', value:'Business Intelligence Analyst' },
          { name: 'Chief Information Officer (CIO)', value:'Chief Information Officer (CIO)' },
          { name: 'Chief Technology Officer (CTO)', value:'Chief Technology Officer (CTO)' },
          { name: 'Cloud Computing Engineer', value:'Cloud Computing Engineer' },
          { name: 'Customer Support Technician', value:'Customer Support Technician' },
          { name: 'Cybersecurity Manager', value:'Cybersecurity Manager' },
          { name: 'Database Developer', value:'Database Developer' },
          { name: 'Digital Project Manager', value:'Digital Project Manager' },
          { name: 'E-commerce Manager', value:'E-commerce Manager' },
          { name: 'Front-end Web Developer', value:'Front-end Web Developer' },
          { name: 'Full-stack Web Developer', value:'Full-stack Web Developer' },
          { name: 'Help Desk Technician', value:'Help Desk Technician' },
          { name: 'Incident Responder', value:'Incident Responder' },
          { name: 'Information Technology Manager', value:'Information Technology Manager' },
          { name: 'IT Business Analyst', value:'IT Business Analyst' },
          { name: 'IT Operations Manager', value:'IT Operations Manager' },
          { name: 'IT Security Manager', value:'IT Security Manager' },
          { name: 'IT Service Desk Manager', value:'IT Service Desk Manager' },
          { name: 'IT Support Analyst', value:'IT Support Analyst' },
          { name: 'IT Systems Manager', value:'IT Systems Manager' },
          { name: 'JavaScript Engineer', value:'JavaScript Engineer' },
          { name: 'Lead Software Developer', value:'Lead Software Developer' },
          { name: 'Machine Learning Scientist', value:'Machine Learning Scientist' },
          { name: 'Mobile Application Designer', value:'Mobile Application Designer' },
          { name: 'Network Support Technician', value:'Network Support Technician' },
          { name: 'Operations Analyst', value:'Operations Analyst' },
          { name: 'Product Owner', value:'Product Owner' },
          { name: 'Project Coordinator', value:'Project Coordinator' },
          { name: 'Python Engineer', value:'Python Engineer' },
          { name: 'Quality Assurance Manager', value:'Quality Assurance Manager' },
          { name: 'Security Analyst', value:'Security Analyst' },
          { name: 'Software Development Manager', value:'Software Development Manager' },
          { name: 'Software Product Manager', value:'Software Product Manager' },
          { name: 'Software Quality Assurance Engineer', value:'Software Quality Assurance Engineer' },
          { name: 'Software Tester', value:'Software Tester' },
          { name: 'Solutions Engineer', value:'Solutions Engineer' },         
        ];
          
    }
}